name: Production Workflow - Build and deploy to production

on:
  pull_request:
    types: closed
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests, collect static files and create app.yaml
      run: |
        python manage.py test --exclude-tag=functional
        python manage.py collectstatic --noinput
        python app.yaml.py
      env:
        # Django
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        DEBUG: ${{secrets.DEBUG}}
      
    - name: Decrypt App Engine service account
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GAE_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GAE_SA_KEY}}
      
    - name: Deploy the app to App Engine Standard
      run: |
        chmod +x .github/scripts/deploy-gae.sh
        ./.github/scripts/deploy-gae.sh
      env:
        GAE_SA_KEY: ${{secrets.GAE_SA_KEY }}
        GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
